# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161006_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
