# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161007_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
